# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'mainUI.ui'
##
## Created by: Qt User Interface Compiler version 6.7.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide2.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide2.QtWidgets import (QApplication, QComboBox, QLabel, QMainWindow,
    QMenuBar, QPlainTextEdit, QPushButton, QSizePolicy,
    QStatusBar, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(800, 440)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.leftButton = QPushButton(self.centralwidget)
        self.leftButton.setObjectName(u"leftButton")
        self.leftButton.setGeometry(QRect(20, 210, 81, 81))
        font = QFont()
        font.setPointSize(18)
        self.leftButton.setFont(font)
        self.logText = QPlainTextEdit(self.centralwidget)
        self.logText.setObjectName(u"logText")
        self.logText.setGeometry(QRect(30, 20, 321, 81))
        font1 = QFont()
        font1.setFamilies([u"Consolas"])
        self.logText.setFont(font1)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(30, -10, 121, 31))
        self.midButton = QPushButton(self.centralwidget)
        self.midButton.setObjectName(u"midButton")
        self.midButton.setGeometry(QRect(110, 210, 81, 81))
        font2 = QFont()
        font2.setPointSize(16)
        font2.setBold(True)
        self.midButton.setFont(font2)
        self.midButton.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.rightButton = QPushButton(self.centralwidget)
        self.rightButton.setObjectName(u"rightButton")
        self.rightButton.setGeometry(QRect(200, 210, 81, 81))
        self.rightButton.setFont(font)
        self.backButton = QPushButton(self.centralwidget)
        self.backButton.setObjectName(u"backButton")
        self.backButton.setGeometry(QRect(110, 300, 81, 81))
        font3 = QFont()
        font3.setPointSize(12)
        self.backButton.setFont(font3)
        self.goButton = QPushButton(self.centralwidget)
        self.goButton.setObjectName(u"goButton")
        self.goButton.setGeometry(QRect(110, 120, 81, 81))
        self.goButton.setFont(font3)
        self.stopButton = QPushButton(self.centralwidget)
        self.stopButton.setObjectName(u"stopButton")
        self.stopButton.setGeometry(QRect(680, 300, 101, 81))
        self.stopButton.setFont(font2)
        self.stopButton.setStyleSheet(u"color: rgb(255, 0, 0);")
        self.voiceButton = QPushButton(self.centralwidget)
        self.voiceButton.setObjectName(u"voiceButton")
        self.voiceButton.setGeometry(QRect(570, 300, 101, 81))
        font4 = QFont()
        font4.setPointSize(16)
        self.voiceButton.setFont(font4)
        self.startButton = QPushButton(self.centralwidget)
        self.startButton.setObjectName(u"startButton")
        self.startButton.setGeometry(QRect(460, 300, 101, 81))
        self.startButton.setFont(font4)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(200, 140, 91, 21))
        self.zoneLabel = QLabel(self.centralwidget)
        self.zoneLabel.setObjectName(u"zoneLabel")
        self.zoneLabel.setGeometry(QRect(390, 140, 71, 21))
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(350, 140, 41, 20))
        self.cam = QLabel(self.centralwidget)
        self.cam.setObjectName(u"cam")
        self.cam.setGeometry(QRect(460, 20, 224, 224))
        self.cam.setStyleSheet(u"background-color: rgb(255, 255, 255);")
        self.comboBox = QComboBox(self.centralwidget)
        self.comboBox.addItem("")
        self.comboBox.setObjectName(u"comboBox")
        self.comboBox.setGeometry(QRect(310, 220, 121, 22))
        self.comboBox_2 = QComboBox(self.centralwidget)
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.setObjectName(u"comboBox_2")
        self.comboBox_2.setGeometry(QRect(310, 260, 121, 22))
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(200, 160, 141, 21))
        self.distanceLabel = QLabel(self.centralwidget)
        self.distanceLabel.setObjectName(u"distanceLabel")
        self.distanceLabel.setGeometry(QRect(350, 160, 71, 21))
        self.pushButton = QPushButton(self.centralwidget)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(20, 120, 81, 81))
        self.pushButton_2 = QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(20, 300, 81, 81))
        self.pushButton_3 = QPushButton(self.centralwidget)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(700, 120, 81, 81))
        self.pushButton_4 = QPushButton(self.centralwidget)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(700, 210, 81, 81))
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QMenuBar(MainWindow)
        self.menubar.setObjectName(u"menubar")
        self.menubar.setGeometry(QRect(0, 0, 800, 22))
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        self.stopButton.clicked.connect(MainWindow.emergencyBreak)
        self.voiceButton.pressed.connect(MainWindow.startRecording)
        self.rightButton.pressed.connect(MainWindow.right)
        self.goButton.pressed.connect(MainWindow.go)
        self.midButton.clicked.connect(MainWindow.emergencyBreak)
        self.backButton.pressed.connect(MainWindow.back)
        self.leftButton.pressed.connect(MainWindow.left)
        self.startButton.clicked.connect(MainWindow.follow)
        self.goButton.released.connect(MainWindow.stop)
        self.leftButton.released.connect(MainWindow.stop)
        self.backButton.released.connect(MainWindow.stop)
        self.rightButton.released.connect(MainWindow.stop)
        self.comboBox_2.currentIndexChanged.connect(MainWindow.changeLanguage)
        self.voiceButton.released.connect(MainWindow.stopRecording)
        self.pushButton.pressed.connect(MainWindow.up)
        self.pushButton.released.connect(MainWindow.stop)
        self.pushButton_2.pressed.connect(MainWindow.down)
        self.pushButton_2.released.connect(MainWindow.stop)
        self.pushButton_3.pressed.connect(MainWindow.grab)
        self.pushButton_3.released.connect(MainWindow.stop)
        self.pushButton_4.pressed.connect(MainWindow.release)
        self.pushButton_4.released.connect(MainWindow.stop)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.leftButton.setText(QCoreApplication.translate("MainWindow", u"\u21b6", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"Sensor log", None))
        self.midButton.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.rightButton.setText(QCoreApplication.translate("MainWindow", u"\u21b7", None))
        self.backButton.setText(QCoreApplication.translate("MainWindow", u"\u25bc", None))
        self.goButton.setText(QCoreApplication.translate("MainWindow", u"\u25b2", None))
        self.stopButton.setText(QCoreApplication.translate("MainWindow", u"STOP", None))
        self.voiceButton.setText(QCoreApplication.translate("MainWindow", u"VOICE", None))
        self.startButton.setText(QCoreApplication.translate("MainWindow", u"Follow", None))
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Current Zone:", None))
        self.zoneLabel.setText(QCoreApplication.translate("MainWindow", u"Unknown", None))
        self.label_4.setText(QCoreApplication.translate("MainWindow", u"Zone", None))
        self.cam.setText("")
        self.comboBox.setItemText(0, QCoreApplication.translate("MainWindow", u"AGV 0", None))

        self.comboBox.setCurrentText("")
        self.comboBox.setPlaceholderText(QCoreApplication.translate("MainWindow", u"AGV ID", None))
        self.comboBox_2.setItemText(0, QCoreApplication.translate("MainWindow", u"English", None))
        self.comboBox_2.setItemText(1, QCoreApplication.translate("MainWindow", u"Korean", None))
        self.comboBox_2.setItemText(2, QCoreApplication.translate("MainWindow", u"Fran\u00e7ais", None))
        self.comboBox_2.setItemText(3, QCoreApplication.translate("MainWindow", u"\u4e2d\u6587", None))

        self.comboBox_2.setPlaceholderText(QCoreApplication.translate("MainWindow", u"Voice Language", None))
        self.label_5.setText(QCoreApplication.translate("MainWindow", u"Distance to obstacle", None))
        self.distanceLabel.setText(QCoreApplication.translate("MainWindow", u"Unknown", None))
        self.pushButton.setText(QCoreApplication.translate("MainWindow", u"Arm\n"
"UP", None))
        self.pushButton_2.setText(QCoreApplication.translate("MainWindow", u"Arm\n"
"DOWN", None))
        self.pushButton_3.setText(QCoreApplication.translate("MainWindow", u"Grab", None))
        self.pushButton_4.setText(QCoreApplication.translate("MainWindow", u"Release", None))
    # retranslateUi

